"""TRACE task implementations."""

from .registry import TASK_REGISTRY, create_task
from .geometry.analytical_2d import area as _task_geometry_analytical_2d_area
from .geometry.analytical_2d import composite_area as _task_geometry_analytical_2d_composite_area
from .geometry.analytical_2d import length as _task_geometry_analytical_2d_length
from .geometry.analytical_2d import perimeter as _task_geometry_analytical_2d_perimeter
from .geometry.analytical_3d import surface_area as _task_geometry_analytical_3d_surface_area
from .geometry.analytical_3d import volume as _task_geometry_analytical_3d_volume
from .geometry.comparison import angle as _task_geometry_comparison_angle
from .geometry.comparison import area as _task_geometry_comparison_area
from .geometry.comparison import length as _task_geometry_comparison_length
from .geometry.comparison import perimeter as _task_geometry_comparison_perimeter
from .geometry.counting import angle as _task_geometry_counting_angle
from .geometry.counting import convexity as _task_geometry_counting_convexity
from .geometry.counting import quadrilateral as _task_geometry_counting_quadrilateral
from .geometry.counting import shape_type as _task_geometry_counting_shape_type
from .geometry.counting import triangle as _task_geometry_counting_triangle
from .geometry.measurement import angle as _task_geometry_measurement_angle
from .geometry.measurement import area as _task_geometry_measurement_area
from .geometry.measurement import length as _task_geometry_measurement_length
from .geometry.measurement import perimeter as _task_geometry_measurement_perimeter
from .geometry.measurement import slope as _task_geometry_measurement_slope
from .graph.comparison import largest_component_size as _task_graph_comparison_largest_component_size
from .graph.counting import articulation_point_count as _task_graph_counting_articulation_point_count
from .graph.counting import degree_count as _task_graph_counting_degree_count
from .graph.path import shortest_path_length as _task_graph_path_shortest_path_length
from .graph.relation import same_component_count as _task_graph_relation_same_component_count
from .graph.relation import unique_cycle_size as _task_graph_relation_unique_cycle_size
from .icons.counting import color as _task_icons_counting_color
from .icons.counting import attribute_binding as _task_icons_counting_attribute_binding
from .icons.counting import orientation as _task_icons_counting_orientation
from .icons.counting import size_relation as _task_icons_counting_size_relation
from .icons.counting import singleton_type as _task_icons_counting_singleton_type
from .icons.counting import type as _task_icons_counting_type
from .icons.relation import between_two_anchors_count as _task_icons_relation_between_two_anchors_count
from .icons.relation import mirror_symmetry as _task_icons_relation_mirror_symmetry
from .icons.relation import occlusion_order as _task_icons_relation_occlusion_order
from .icons.relation import relative_position_type as _task_icons_relation_relative_position_type
from .icons.pattern import grid_rotation_violation as _task_icons_pattern_grid_rotation_violation
from .icons.pattern import grid_size_violation as _task_icons_pattern_grid_size_violation
from .icons.sequence import missing_count as _task_icons_sequence_missing_count
from .icons.sequence import rotation_violation as _task_icons_sequence_rotation_violation
from .icons.transformation import pair_count as _task_icons_transformation_pair_count
from .charts.composition import subset_value as _task_charts_composition_subset_value
from .charts.counting import value_count as _task_charts_counting_value_count
from .charts.distribution import boxplot_label as _task_charts_distribution_boxplot_label
from .charts.distribution import density_label as _task_charts_distribution_density_label
from .charts.distribution import histogram_count as _task_charts_distribution_histogram_count
from .charts.multiseries import pairwise_comparison_count as _task_charts_multiseries_pairwise_comparison_count
from .charts.readout import subset_value as _task_charts_readout_subset_value
from .charts.statistics import summary_label as _task_charts_statistics_summary_label
from .charts.statistics import summary_value as _task_charts_statistics_summary_value
from .charts.trend import structure_value as _task_charts_trend_structure_value
from .tables.counting import value_count as _task_tables_counting_value_count
from .tables.ranking import label as _task_tables_ranking_label
from .tables.relation import extremum_transfer_value as _task_tables_relation_extremum_transfer_value
from .tables.relation import row_compare_label as _task_tables_relation_row_compare_label
from .tables.readout import subset_value as _task_tables_readout_subset_value
from .tables.statistics import filtered_subset_value as _task_tables_statistics_filtered_subset_value
from .tables.statistics import filtered_subset_label as _task_tables_statistics_filtered_subset_label
from .tables.statistics import summary_label as _task_tables_statistics_summary_label
from .tables.statistics import summary_value as _task_tables_statistics_summary_value
from .tables.temporal import value as _task_tables_temporal_value
from .tile import count_color_components as _task_tile_count_color_components
from .tile import count_color_count as _task_tile_count_color_count
from .tile import count_largest_component_size as _task_tile_count_largest_component_size
from .tile import path_reachable_target_count as _task_tile_path_reachable_target_count
from .tile import path_shortest_path as _task_tile_path_shortest_path
from .tile import pattern_match3_run_count as _task_tile_pattern_match3_run_count
from .tile import reachability_region_size as _task_tile_reachability_region_size
from .tile import relation_min_distance as _task_tile_relation_min_distance
from .tile import symmetry_violation_count as _task_tile_symmetry_violation_count
from .tile import transition_gravity_max_drop as _task_tile_transition_gravity_max_drop

__all__ = [
    "TASK_REGISTRY",
    "create_task",
]
