"""Compute the double-cone volume generated by rotating a triangle."""

from __future__ import annotations

from trace.core.types import TypedValue
from trace.tasks.base import TaskOutput
from trace.tasks.registry import register_task
from trace.tasks.shared.fixed_query import select_task_query_id

from ._lifecycle import build_solid_revolution_plan, prepare_solid_revolution_task_parts
from .shared.defaults import DOMAIN, SCENE_ID
from .shared.measurements import answer_support_probability_map, round_volume, volume_double_cone
from .shared.rendering import render_double_cone_revolution
from .shared.sampling import double_cone_case_pool, select_case_from_pool, support_from_cases
from .shared.state import SolidRevolutionProblem

TASK_ID = "task_geometry__solid_revolution__revolution_double_cone_volume_value"
QUERY_ID = "single"
SUPPORTED_QUERY_IDS = (QUERY_ID,)
ANNOTATION_KEYS = (
    "source_diagram_bbox",
    "resulting_solid_bbox",
)


def _prepare_double_cone_objective(
    *,
    instance_seed,
    params,
    selected_query,
    branch_probabilities,
):
    # This task binds double-cone measurements and volume before rendering.
    cases = double_cone_case_pool()
    case = select_case_from_pool(
        instance_seed=instance_seed,
        params=params,
        namespace=f"{TASK_ID}.{selected_query}.case",
        cases=cases,
    )
    support = support_from_cases(cases)
    support_probabilities = answer_support_probability_map(support, case.answer)
    answer = round_volume(volume_double_cone(radius=case.radius, half_height=case.half_height))
    problem = SolidRevolutionProblem(
        solid_kind="double_cone",
        generating_shape="isosceles_triangle",
        answer=answer,
        formula_family="double_cone_volume_from_triangle",
        formula="V = 2 * (1/3) pi r^2 h",
        radius=float(case.radius),
        half_height=float(case.half_height),
        total_height=float(2 * case.half_height),
        answer_support_probabilities=support_probabilities,
        construction_case_count_for_answer=1,
    )
    return build_solid_revolution_plan(
        prompt_key=QUERY_ID,
        problem=problem,
        render_scene=render_double_cone_revolution,
        annotation_keys=ANNOTATION_KEYS,
        branch_probabilities=branch_probabilities,
        support_probabilities=support_probabilities,
    )


@register_task
class GeometrySolidRevolutionDoubleConeVolumeValueTask:
    task_id = TASK_ID
    reasoning_operations = ('transformation', 'formula_evaluation')
    domain = DOMAIN
    default_dataset_enabled = True
    supported_query_ids = SUPPORTED_QUERY_IDS
    default_query_id = QUERY_ID

    @staticmethod
    def _bind_double_cone_plan(instance_seed: int, params: dict, query_id: str, query_probabilities: dict) -> object:
        """Bind the double-cone target volume and prompt/annotation roles."""

        return _prepare_double_cone_objective(
            instance_seed=int(instance_seed),
            params=params,
            selected_query=str(query_id),
            branch_probabilities=query_probabilities,
        )

    @staticmethod
    def _emit_output(*, parts, plan, query_id: str) -> TaskOutput:
        """Return the public task output after task-owned answer binding."""

        return TaskOutput(
            prompt=parts.prompt,
            answer_gt=TypedValue(type="number", value=float(plan.answer_value)),
            annotation_gt=TypedValue(type="bbox_map", value=dict(parts.annotation_value)),
            image=parts.image,
            image_id="img0",
            trace_payload=parts.trace_payload,
            task_versions=parts.task_versions,
            scene_id=SCENE_ID,
            query_id=str(query_id),
            prompt_variants=dict(parts.prompt_variants),
        )

    def generate(self, instance_seed: int, *, params: dict, max_attempts: int) -> TaskOutput:
        """Generate one double-cone revolution volume task with task-owned output binding."""

        selected_query, probabilities, task_params = select_task_query_id(
            instance_seed=int(instance_seed),
            params=params,
            supported_query_ids=SUPPORTED_QUERY_IDS,
            default_query_id=QUERY_ID,
            task_id=TASK_ID,
            namespace=f"{TASK_ID}.query",
        )
        plan = self._bind_double_cone_plan(
            int(instance_seed),
            task_params,
            str(selected_query),
            dict(probabilities),
        )
        parts = prepare_solid_revolution_task_parts(
            task_id=TASK_ID,
            selected_query=str(selected_query),
            branch_probabilities=probabilities,
            params=task_params,
            plan=plan,
            instance_seed=int(instance_seed),
            max_attempts=int(max_attempts),
        )
        return self._emit_output(parts=parts, plan=plan, query_id=str(selected_query))


__all__ = [
    "ANNOTATION_KEYS",
    "GeometrySolidRevolutionDoubleConeVolumeValueTask",
    "SCENE_ID",
    "SUPPORTED_QUERY_IDS",
    "TASK_ID",
]
