"""Compute the frustum volume generated by rotating a trapezoid."""

from __future__ import annotations

from trace.tasks.registry import register_task

from ._lifecycle import build_solid_revolution_plan, run_solid_revolution_public_entry
from .shared.defaults import SCENE_ID
from .shared.measurements import answer_support_probability_map, round_volume, volume_frustum
from .shared.rendering import render_frustum_revolution
from .shared.sampling import frustum_case_pool, select_case_from_pool, support_from_cases
from .shared.state import SolidRevolutionProblem

TASK_ID = "task_geometry__solid_revolution__revolution_frustum_volume_value"
QUERY_ID = "single"
SUPPORTED_QUERY_IDS = (QUERY_ID,)
ANNOTATION_KEYS = (
    "generating_shape",
    "rotation_axis",
    "solid_preview",
    "target_volume_cue",
    "height_label",
    "top_radius_label",
    "bottom_radius_label",
)


def _prepare_frustum_objective(
    *,
    instance_seed,
    params,
    selected_query,
    branch_probabilities,
):
    # This task binds frustum measurements and volume before rendering.
    cases = frustum_case_pool()
    case = select_case_from_pool(
        instance_seed=instance_seed,
        params=params,
        namespace=f"{TASK_ID}.{selected_query}.case",
        cases=cases,
    )
    support = support_from_cases(cases)
    support_probabilities = answer_support_probability_map(support, case.answer)
    answer = round_volume(
        volume_frustum(
            top_radius=case.top_radius,
            bottom_radius=case.bottom_radius,
            height=case.height,
        )
    )
    problem = SolidRevolutionProblem(
        solid_kind="frustum",
        generating_shape="right_trapezoid",
        answer=answer,
        formula_family="frustum_volume_from_trapezoid",
        formula="V = (1/3) pi h (R^2 + Rr + r^2)",
        top_radius=float(case.top_radius),
        bottom_radius=float(case.bottom_radius),
        height=float(case.height),
        answer_support_probabilities=support_probabilities,
        construction_case_count_for_answer=1,
    )
    return build_solid_revolution_plan(
        prompt_key=QUERY_ID,
        problem=problem,
        render_scene=render_frustum_revolution,
        annotation_keys=ANNOTATION_KEYS,
        branch_probabilities=branch_probabilities,
        support_probabilities=support_probabilities,
    )


@register_task
class GeometrySolidRevolutionFrustumVolumeValueTask:
    task_id = TASK_ID
    domain = "geometry"
    default_dataset_enabled = True
    supported_query_ids = SUPPORTED_QUERY_IDS
    default_query_id = QUERY_ID
    prepare_objective = staticmethod(_prepare_frustum_objective)

    def generate(self, instance_seed, *, params, max_attempts):
        return run_solid_revolution_public_entry(
            self,
            instance_seed,
            params=params,
            max_attempts=max_attempts,
        )


__all__ = [
    "ANNOTATION_KEYS",
    "GeometrySolidRevolutionFrustumVolumeValueTask",
    "SCENE_ID",
    "SUPPORTED_QUERY_IDS",
    "TASK_ID",
]
