"""Compute the cone volume generated by rotating a right triangle."""

from __future__ import annotations

from trace.core import types as core_types
from trace.tasks import base as task_base
from trace.tasks import registry as task_registry
from trace.tasks.shared import fixed_query

from . import _lifecycle as lifecycle
from .shared.defaults import DOMAIN, SCENE_ID
from .shared.measurements import answer_support_probability_map, round_volume, volume_cone
from .shared.rendering import render_cone_revolution
from .shared import sampling as revolution_sampling
from .shared.state import SolidRevolutionProblem

CONE_TASK_ID = "task_geometry__solid_revolution__revolution_cone_volume_value"
CONE_QUERY_ID = "single"
CONE_QUERY_IDS = (CONE_QUERY_ID,)
CONE_ANNOTATION_KEYS = (
    "source_diagram_bbox",
    "resulting_solid_bbox",
)


def _prepare_cone_objective(
    *,
    instance_seed,
    params,
    selected_query,
    branch_probabilities,
):
    # This task binds cone measurements and volume before rendering.
    cases = revolution_sampling.cone_case_pool()
    case = revolution_sampling.select_case_from_pool(
        instance_seed=instance_seed,
        params=params,
        namespace=f"{CONE_TASK_ID}.{selected_query}.case",
        cases=cases,
    )
    support = revolution_sampling.support_from_cases(cases)
    support_probabilities = answer_support_probability_map(support, case.answer)
    answer = round_volume(volume_cone(radius=case.radius, height=case.height))
    problem = SolidRevolutionProblem(
        solid_kind="cone",
        generating_shape="right_triangle",
        answer=answer,
        formula_family="cone_volume_from_right_triangle",
        formula="r^2 = l^2 - h^2, then V = (1/3) pi r^2 h",
        radius=float(case.radius),
        height=float(case.height),
        slant_height=float(case.slant_height),
        answer_support_probabilities=support_probabilities,
        construction_case_count_for_answer=1,
    )
    return lifecycle.build_solid_revolution_plan(
        prompt_key=CONE_QUERY_ID,
        problem=problem,
        render_scene=render_cone_revolution,
        annotation_keys=CONE_ANNOTATION_KEYS,
        branch_probabilities=branch_probabilities,
        support_probabilities=support_probabilities,
    )


@task_registry.register_task
class GeometrySolidRevolutionConeVolumeValueTask:
    task_id = CONE_TASK_ID
    domain = DOMAIN
    default_dataset_enabled = True
    supported_query_ids = CONE_QUERY_IDS
    default_query_id = CONE_QUERY_ID

    def generate(self, instance_seed: int, *, params: dict, max_attempts: int) -> task_base.TaskOutput:
        """Generate one cone-revolution volume task with task-owned output binding."""

        selected_query, query_probabilities, task_params = fixed_query.select_task_query_id(
            instance_seed=int(instance_seed),
            params=params,
            supported_query_ids=CONE_QUERY_IDS,
            default_query_id=CONE_QUERY_ID,
            task_id=CONE_TASK_ID,
            namespace=f"{CONE_TASK_ID}.query",
        )
        plan = _prepare_cone_objective(
            instance_seed=int(instance_seed),
            params=task_params,
            selected_query=str(selected_query),
            branch_probabilities=query_probabilities,
        )
        parts = lifecycle.prepare_solid_revolution_task_parts(
            task_id=CONE_TASK_ID,
            selected_query=str(selected_query),
            branch_probabilities=query_probabilities,
            params=task_params,
            plan=plan,
            instance_seed=int(instance_seed),
            max_attempts=int(max_attempts),
        )
        return task_base.TaskOutput(
            prompt=parts.prompt,
            answer_gt=core_types.TypedValue(type="number", value=float(plan.answer_value)),
            annotation_gt=core_types.TypedValue(type="bbox_map", value=dict(parts.annotation_value)),
            image=parts.image,
            image_id="img0",
            trace_payload=parts.trace_payload,
            task_versions=parts.task_versions,
            scene_id=SCENE_ID,
            query_id=str(selected_query),
            prompt_variants=dict(parts.prompt_variants),
        )


# Backward-compatible module constants for focused scene tests.
TASK_ID = CONE_TASK_ID
SUPPORTED_QUERY_IDS = CONE_QUERY_IDS
ANNOTATION_KEYS = CONE_ANNOTATION_KEYS

__all__ = [
    "ANNOTATION_KEYS",
    "CONE_ANNOTATION_KEYS",
    "CONE_QUERY_IDS",
    "CONE_TASK_ID",
    "GeometrySolidRevolutionConeVolumeValueTask",
    "SCENE_ID",
    "SUPPORTED_QUERY_IDS",
    "TASK_ID",
]
