"""Compute the frustum volume generated by rotating a trapezoid."""

from __future__ import annotations

from dataclasses import dataclass

from trace.core.types import TypedValue
from trace.tasks.base import TaskOutput
from trace.tasks.registry import register_task
from trace.tasks.shared.fixed_query import select_task_query_id

from ._lifecycle import build_solid_revolution_plan, prepare_solid_revolution_task_parts
from .shared.defaults import DOMAIN, SCENE_ID
from .shared.measurements import answer_support_probability_map, round_volume, volume_frustum
from .shared.rendering import render_frustum_revolution
from .shared.sampling import frustum_case_pool, select_case_from_pool, support_from_cases
from .shared.state import SolidRevolutionProblem

TASK_ID = "task_geometry__solid_revolution__revolution_frustum_volume_value"
QUERY_ID = "single"
SUPPORTED_QUERY_IDS = (QUERY_ID,)
ANNOTATION_KEYS = (
    "source_diagram_bbox",
    "resulting_solid_bbox",
)


@dataclass(frozen=True)
class FrustumVolumeBinding:
    """Task-local selected frustum case and one-hot answer support."""

    problem: SolidRevolutionProblem
    support_probabilities: dict[str, float]


def _select_frustum_binding(*, instance_seed: int, params: dict, query_id: str) -> FrustumVolumeBinding:
    """Select a frustum construction and bind the public volume objective."""

    cases = frustum_case_pool()
    case = select_case_from_pool(
        instance_seed=int(instance_seed),
        params=params,
        namespace=f"{TASK_ID}.{query_id}.case",
        cases=cases,
    )
    support_probabilities = answer_support_probability_map(support_from_cases(cases), case.answer)
    answer = round_volume(
        volume_frustum(
            top_radius=case.top_radius,
            bottom_radius=case.bottom_radius,
            height=case.height,
        )
    )
    problem = SolidRevolutionProblem(
        solid_kind="frustum",
        generating_shape="right_trapezoid",
        answer=answer,
        formula_family="frustum_volume_from_trapezoid",
        formula="V = (1/3) pi h (R^2 + Rr + r^2)",
        top_radius=float(case.top_radius),
        bottom_radius=float(case.bottom_radius),
        height=float(case.height),
        answer_support_probabilities=support_probabilities,
        construction_case_count_for_answer=1,
    )
    return FrustumVolumeBinding(
        problem=problem,
        support_probabilities=support_probabilities,
    )


@register_task
class GeometrySolidRevolutionFrustumVolumeValueTask:
    task_id = TASK_ID
    reasoning_operations = ('transformation', 'formula_evaluation')
    domain = DOMAIN
    default_dataset_enabled = True
    supported_query_ids = SUPPORTED_QUERY_IDS
    default_query_id = QUERY_ID

    def generate(self, instance_seed: int, *, params: dict, max_attempts: int) -> TaskOutput:
        """Generate one frustum-revolution volume task with task-owned output binding."""

        query_id, query_probabilities, resolved_params = select_task_query_id(
            instance_seed=int(instance_seed),
            params=params,
            supported_query_ids=SUPPORTED_QUERY_IDS,
            default_query_id=QUERY_ID,
            task_id=TASK_ID,
            namespace=f"{TASK_ID}.query",
        )
        binding = _select_frustum_binding(
            instance_seed=int(instance_seed),
            params=resolved_params,
            query_id=str(query_id),
        )
        plan = build_solid_revolution_plan(
            prompt_key=QUERY_ID,
            problem=binding.problem,
            render_scene=render_frustum_revolution,
            annotation_keys=ANNOTATION_KEYS,
            branch_probabilities=query_probabilities,
            support_probabilities=binding.support_probabilities,
        )
        parts = prepare_solid_revolution_task_parts(
            task_id=TASK_ID,
            selected_query=str(query_id),
            branch_probabilities=query_probabilities,
            params=resolved_params,
            plan=plan,
            instance_seed=int(instance_seed),
            max_attempts=int(max_attempts),
        )
        answer = TypedValue(type="number", value=float(plan.answer_value))
        annotation = TypedValue(type="bbox_map", value=dict(parts.annotation_value))
        return TaskOutput(
            parts.prompt,
            answer,
            annotation,
            parts.image,
            "img0",
            parts.trace_payload,
            parts.task_versions,
            SCENE_ID,
            str(query_id),
            dict(parts.prompt_variants),
        )


__all__ = [
    "ANNOTATION_KEYS",
    "GeometrySolidRevolutionFrustumVolumeValueTask",
    "SCENE_ID",
    "SUPPORTED_QUERY_IDS",
    "TASK_ID",
]
