"""Compute the double-cone volume generated by rotating a triangle."""

from __future__ import annotations

from trace.tasks.registry import register_task

from ._lifecycle import build_solid_revolution_plan, run_solid_revolution_public_entry
from .shared.defaults import SCENE_ID
from .shared.measurements import answer_support_probability_map, round_volume, volume_double_cone
from .shared.rendering import render_double_cone_revolution
from .shared.sampling import double_cone_case_pool, select_case_from_pool, support_from_cases
from .shared.state import SolidRevolutionProblem

TASK_ID = "task_geometry__solid_revolution__revolution_double_cone_volume_value"
QUERY_ID = "single"
SUPPORTED_QUERY_IDS = (QUERY_ID,)
ANNOTATION_KEYS = (
    "generating_shape",
    "rotation_axis",
    "solid_preview",
    "target_volume_cue",
    "half_height_label",
    "radius_label",
)


def _prepare_double_cone_objective(
    *,
    instance_seed,
    params,
    selected_query,
    branch_probabilities,
):
    # This task binds double-cone measurements and volume before rendering.
    cases = double_cone_case_pool()
    case = select_case_from_pool(
        instance_seed=instance_seed,
        params=params,
        namespace=f"{TASK_ID}.{selected_query}.case",
        cases=cases,
    )
    support = support_from_cases(cases)
    support_probabilities = answer_support_probability_map(support, case.answer)
    answer = round_volume(volume_double_cone(radius=case.radius, half_height=case.half_height))
    problem = SolidRevolutionProblem(
        solid_kind="double_cone",
        generating_shape="isosceles_triangle",
        answer=answer,
        formula_family="double_cone_volume_from_triangle",
        formula="V = 2 * (1/3) pi r^2 h",
        radius=float(case.radius),
        half_height=float(case.half_height),
        total_height=float(2 * case.half_height),
        answer_support_probabilities=support_probabilities,
        construction_case_count_for_answer=1,
    )
    return build_solid_revolution_plan(
        prompt_key=QUERY_ID,
        problem=problem,
        render_scene=render_double_cone_revolution,
        annotation_keys=ANNOTATION_KEYS,
        branch_probabilities=branch_probabilities,
        support_probabilities=support_probabilities,
    )


@register_task
class GeometrySolidRevolutionDoubleConeVolumeValueTask:
    task_id = TASK_ID
    domain = "geometry"
    default_dataset_enabled = True
    supported_query_ids = SUPPORTED_QUERY_IDS
    default_query_id = QUERY_ID
    prepare_objective = staticmethod(_prepare_double_cone_objective)

    def generate(self, instance_seed, *, params, max_attempts):
        return run_solid_revolution_public_entry(
            self,
            instance_seed,
            params=params,
            max_attempts=max_attempts,
        )


__all__ = [
    "ANNOTATION_KEYS",
    "GeometrySolidRevolutionDoubleConeVolumeValueTask",
    "SCENE_ID",
    "SUPPORTED_QUERY_IDS",
    "TASK_ID",
]
