"""Compute the cylinder volume generated by rotating a rectangle."""

from __future__ import annotations

from trace.tasks.registry import register_task

from ._lifecycle import build_solid_revolution_plan, run_solid_revolution_public_entry
from .shared.defaults import SCENE_ID
from .shared.measurements import answer_support_probability_map, round_volume, volume_cylinder
from .shared.rendering import render_cylinder_revolution
from .shared.sampling import cylinder_case_pool, select_case_from_pool, support_from_cases
from .shared.state import SolidRevolutionProblem

TASK_ID = "task_geometry__solid_revolution__revolution_cylinder_volume_value"
QUERY_ID = "single"
SUPPORTED_QUERY_IDS = (QUERY_ID,)
ANNOTATION_KEYS = (
    "generating_shape",
    "rotation_axis",
    "solid_preview",
    "target_volume_cue",
    "height_label",
    "radial_input_label",
)


def _prepare_cylinder_objective(
    *,
    instance_seed,
    params,
    selected_query,
    branch_probabilities,
):
    # This task binds cylinder dimensions and volume before rendering.
    cases = cylinder_case_pool()
    case = select_case_from_pool(
        instance_seed=instance_seed,
        params=params,
        namespace=f"{TASK_ID}.{selected_query}.case",
        cases=cases,
    )
    support = support_from_cases(cases)
    support_probabilities = answer_support_probability_map(support, case.answer)
    if str(case.radial_input_kind) == "diagonal":
        formula = "d^2 = q^2 - h^2, then V = pi (d/2)^2 h"
    else:
        formula = "V = pi (d/2)^2 h"
    answer = round_volume(volume_cylinder(diameter=case.diameter, height=case.height))
    problem = SolidRevolutionProblem(
        solid_kind="cylinder",
        generating_shape="rectangle",
        answer=answer,
        formula_family="cylinder_volume_from_rectangle",
        formula=formula,
        radius=float(case.diameter) / 2.0,
        diameter=float(case.diameter),
        radial_input_kind=str(case.radial_input_kind),
        height=float(case.height),
        diagonal=None if case.diagonal is None else float(case.diagonal),
        answer_support_probabilities=support_probabilities,
        construction_case_count_for_answer=1,
    )
    return build_solid_revolution_plan(
        prompt_key=QUERY_ID,
        problem=problem,
        render_scene=render_cylinder_revolution,
        annotation_keys=ANNOTATION_KEYS,
        branch_probabilities=branch_probabilities,
        support_probabilities=support_probabilities,
    )


@register_task
class GeometrySolidRevolutionCylinderVolumeValueTask:
    task_id = TASK_ID
    domain = "geometry"
    default_dataset_enabled = True
    supported_query_ids = SUPPORTED_QUERY_IDS
    default_query_id = QUERY_ID
    prepare_objective = staticmethod(_prepare_cylinder_objective)

    def generate(self, instance_seed, *, params, max_attempts):
        return run_solid_revolution_public_entry(
            self,
            instance_seed,
            params=params,
            max_attempts=max_attempts,
        )


__all__ = [
    "ANNOTATION_KEYS",
    "GeometrySolidRevolutionCylinderVolumeValueTask",
    "SCENE_ID",
    "SUPPORTED_QUERY_IDS",
    "TASK_ID",
]
