"""Shared styling facade for games-domain tasks."""

from __future__ import annotations

from .style_card_table import (
    CardTheme,
    DominoTheme,
    SUPPORTED_CARD_STYLE_VARIANTS,
    SUPPORTED_DOMINO_STYLE_VARIANTS,
    build_games_card_theme,
    build_games_domino_theme,
    suit_color,
)
from .style_common import SUPPORTED_GAMES_STYLE_VARIANTS, style_probability_map
from .style_node_boards import (
    GoTheme,
    HexTheme,
    NineMensMorrisTheme,
    SUPPORTED_GO_STYLE_VARIANTS,
    SUPPORTED_HEX_STYLE_VARIANTS,
    SUPPORTED_NINE_MENS_MORRIS_STYLE_VARIANTS,
    build_games_go_theme,
    build_games_hex_theme,
    build_games_nine_mens_morris_theme,
)
from .style_number_grids import (
    BattleshipTheme,
    BingoTheme,
    MinesweeperTheme,
    SUPPORTED_BATTLESHIP_STYLE_VARIANTS,
    SUPPORTED_BINGO_STYLE_VARIANTS,
    SUPPORTED_MINESWEEPER_STYLE_VARIANTS,
    build_games_battleship_theme,
    build_games_bingo_theme,
    build_games_minesweeper_theme,
)
from .style_square_boards import (
    CheckersTheme,
    ChessTheme,
    ConnectFourTheme,
    DotsAndBoxesTheme,
    ReversiTheme,
    SUPPORTED_CHECKERS_STYLE_VARIANTS,
    SUPPORTED_CHESS_STYLE_VARIANTS,
    SUPPORTED_CONNECT_FOUR_STYLE_VARIANTS,
    SUPPORTED_DOTS_AND_BOXES_STYLE_VARIANTS,
    SUPPORTED_REVERSI_STYLE_VARIANTS,
    build_games_checkers_theme,
    build_games_chess_theme,
    build_games_connect_four_theme,
    build_games_dots_and_boxes_theme,
    build_games_reversi_theme,
)
from .style_table_surfaces import (
    PoolTheme,
    SUPPORTED_DARTS_STYLE_VARIANTS,
    SUPPORTED_POOL_STYLE_VARIANTS,
    build_games_pool_theme,
)


__all__ = [
    "BattleshipTheme",
    "BingoTheme",
    "CardTheme",
    "CheckersTheme",
    "ChessTheme",
    "ConnectFourTheme",
    "DominoTheme",
    "DotsAndBoxesTheme",
    "GoTheme",
    "HexTheme",
    "MinesweeperTheme",
    "NineMensMorrisTheme",
    "PoolTheme",
    "ReversiTheme",
    "SUPPORTED_CHECKERS_STYLE_VARIANTS",
    "SUPPORTED_CHESS_STYLE_VARIANTS",
    "SUPPORTED_CONNECT_FOUR_STYLE_VARIANTS",
    "SUPPORTED_DARTS_STYLE_VARIANTS",
    "SUPPORTED_DOMINO_STYLE_VARIANTS",
    "SUPPORTED_DOTS_AND_BOXES_STYLE_VARIANTS",
    "SUPPORTED_GAMES_STYLE_VARIANTS",
    "SUPPORTED_BINGO_STYLE_VARIANTS",
    "SUPPORTED_BATTLESHIP_STYLE_VARIANTS",
    "SUPPORTED_CARD_STYLE_VARIANTS",
    "SUPPORTED_GO_STYLE_VARIANTS",
    "SUPPORTED_HEX_STYLE_VARIANTS",
    "SUPPORTED_MINESWEEPER_STYLE_VARIANTS",
    "SUPPORTED_NINE_MENS_MORRIS_STYLE_VARIANTS",
    "SUPPORTED_POOL_STYLE_VARIANTS",
    "SUPPORTED_REVERSI_STYLE_VARIANTS",
    "build_games_battleship_theme",
    "build_games_bingo_theme",
    "build_games_card_theme",
    "build_games_checkers_theme",
    "build_games_chess_theme",
    "build_games_connect_four_theme",
    "build_games_domino_theme",
    "build_games_dots_and_boxes_theme",
    "build_games_go_theme",
    "build_games_hex_theme",
    "build_games_minesweeper_theme",
    "build_games_nine_mens_morris_theme",
    "build_games_pool_theme",
    "build_games_reversi_theme",
    "style_probability_map",
    "suit_color",
]
