"""Chart scene package tasks."""

from .composition_shift_l1_distance import ChartsCompositionPanelsCompositionShiftL1DistanceTask
from .conditioned_panel_sum_from_percent import ChartsCompositionPanelsConditionedPanelSumFromPercentTask
from .segment_count_nearest_target_panel_label import ChartsCompositionPanelsSegmentCountNearestTargetPanelLabelTask
from .segment_count_extremum_panel_label import ChartsCompositionPanelsSegmentCountExtremumPanelLabelTask
from .segment_pair_count_gap_extremum_panel_label import ChartsCompositionPanelsSegmentPairCountGapExtremumPanelLabelTask
from .top_k_by_segment_then_sum_other_segment_count import ChartsCompositionPanelsTopKBySegmentThenSumOtherSegmentCountTask

__all__ = [
    "ChartsCompositionPanelsCompositionShiftL1DistanceTask",
    "ChartsCompositionPanelsConditionedPanelSumFromPercentTask",
    "ChartsCompositionPanelsSegmentCountNearestTargetPanelLabelTask",
    "ChartsCompositionPanelsSegmentCountExtremumPanelLabelTask",
    "ChartsCompositionPanelsSegmentPairCountGapExtremumPanelLabelTask",
    "ChartsCompositionPanelsTopKBySegmentThenSumOtherSegmentCountTask",
]
