#!/usr/bin/env python3
"""Generate the committed active Trace task inventory.

The inventory is intentionally derived from the live default-task registry and
public taxonomy. Narrative docs should link to the generated markdown instead
of repeating active task/scene lists by hand.
"""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path
import sys
from typing import Mapping

import trace.tasks  # noqa: F401 - registers task classes.
from trace.core.taxonomy import ACTIVE_DOMAINS, missing_taxonomy_task_ids, resolve_task_taxonomy
from trace.tasks.registry import list_default_task_ids, list_task_ids


DEFAULT_OUTPUT = Path("docs/ACTIVE_TASK_INVENTORY.md")


def _collect_inventory() -> dict[str, object]:
    default_task_ids = list_default_task_ids()
    registered_task_ids = list_task_ids()
    missing = missing_taxonomy_task_ids(default_task_ids)
    invalid_default_ids = sorted(task_id for task_id in default_task_ids if task_id.startswith("task_") and "__" not in task_id)

    by_domain: dict[str, defaultdict[str, list[str]]] = {
        domain: defaultdict(list) for domain in ACTIVE_DOMAINS
    }
    for task_id in default_task_ids:
        taxonomy = resolve_task_taxonomy(task_id)
        by_domain.setdefault(taxonomy.domain, defaultdict(list))[taxonomy.scene_id].append(task_id)

    domains: dict[str, dict[str, object]] = {}
    for domain in sorted(by_domain):
        scenes = {
            scene_id: sorted(task_ids)
            for scene_id, task_ids in sorted(by_domain[domain].items(), key=lambda item: item[0])
        }
        domains[domain] = {
            "task_count": sum(len(task_ids) for task_ids in scenes.values()),
            "scene_count": len(scenes),
            "scenes": scenes,
        }

    return {
        "default_task_count": len(default_task_ids),
        "registered_task_count": len(registered_task_ids),
        "domain_count": len(domains),
        "scene_count": sum(int(domain["scene_count"]) for domain in domains.values()),
        "missing_taxonomy": missing,
        "invalid_default_ids": invalid_default_ids,
        "domains": domains,
    }


def _markdown_table(headers: list[str], rows: list[list[object]]) -> list[str]:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(str(item) for item in row) + " |")
    return lines


def render_inventory_markdown(inventory: Mapping[str, object] | None = None) -> str:
    """Render the active inventory markdown from live registry metadata."""

    inventory = inventory or _collect_inventory()
    domains = inventory["domains"]
    if not isinstance(domains, Mapping):
        raise TypeError("inventory domains must be a mapping")

    lines: list[str] = [
        "# Active Task Inventory",
        "",
        "Generated by `scripts/generate_active_task_inventory.py` from the live default-task registry and public taxonomy.",
        "Do not edit this file by hand; rerun the generator after active task, scene, or taxonomy changes.",
        "",
        "## Sources",
        "",
        "- Default task ids: `trace.tasks.registry.list_default_task_ids()`",
        "- Registered task ids: `trace.tasks.registry.list_task_ids()`",
        "- Public taxonomy: `trace/core/taxonomy.py`",
        "",
        "## Summary",
        "",
        f"- Default tasks: `{inventory['default_task_count']}`",
        f"- Registered tasks: `{inventory['registered_task_count']}`",
        f"- Public domains: `{inventory['domain_count']}`",
        f"- Public scenes: `{inventory['scene_count']}`",
        f"- Missing taxonomy mappings: `{len(inventory['missing_taxonomy'])}`",
        f"- Invalid default task id shapes: `{len(inventory['invalid_default_ids'])}`",
        "",
        "## Domain Summary",
        "",
    ]

    summary_rows: list[list[object]] = []
    for domain, data in domains.items():
        if not isinstance(data, Mapping):
            raise TypeError("domain inventory must be a mapping")
        summary_rows.append([domain, data["scene_count"], data["task_count"]])
    lines.extend(_markdown_table(["Domain", "Scenes", "Tasks"], summary_rows))
    lines.extend(["", "## Tasks By Domain And Scene", ""])

    for domain, data in domains.items():
        if not isinstance(data, Mapping):
            raise TypeError("domain inventory must be a mapping")
        scenes = data["scenes"]
        if not isinstance(scenes, Mapping):
            raise TypeError("scene inventory must be a mapping")
        lines.extend([f"### {domain}", ""])
        for scene_id, task_ids in scenes.items():
            if not isinstance(task_ids, list):
                raise TypeError("scene task ids must be a list")
            lines.extend([f"#### {scene_id} ({len(task_ids)})", ""])
            for task_id in task_ids:
                lines.append(f"- `{task_id}`")
            lines.append("")

    missing_taxonomy = list(inventory["missing_taxonomy"])
    invalid_default_ids = list(inventory["invalid_default_ids"])
    if missing_taxonomy or invalid_default_ids:
        lines.extend(["## Inventory Warnings", ""])
        for task_id in missing_taxonomy:
            lines.append(f"- Missing taxonomy: `{task_id}`")
        for task_id in invalid_default_ids:
            lines.append(f"- Invalid default task id shape: `{task_id}`")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate docs/ACTIVE_TASK_INVENTORY.md")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    parser.add_argument("--check", action="store_true", help="Fail if the output file is stale.")
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    output = Path(args.output)
    rendered = render_inventory_markdown()
    if args.check:
        existing = output.read_text(encoding="utf-8") if output.exists() else ""
        if existing != rendered:
            print(f"{output} is stale; run `PYTHONPATH=. python scripts/generate_active_task_inventory.py`.", file=sys.stderr)
            return 1
        print(f"{output} is up to date")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")
    print(f"wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
